# Generated by Django 5.1.1 on 2025-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.app.goo.gl/6FMZo8hi7HBmba7w7', max_length=500),
        ),
    ]
